name: CI

on:
    push:
        branches:
            - '*'
    
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ['3.8', '3.9']

        steps:
            - uses: actions/checkout@v4

            - name: List files
              run: ls
                
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip' # caching pip dependencies    

            - name: Install PopulationSim with pip
              run: pip install .
        
