name: CI

on:
    push:
        branches:
            - '*'
    
    pull_request:
        branches:
            - '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true # If another job in the above group wants to run, it will cancel the current job

jobs:
    ci:
        runs-on: ${{ matrix.config.os }}

        name: ${{ matrix.config.os }} (python v${{ matrix.python-version }})

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9']
                config:
                    - {os: macos-latest}
                    - {os: macos-13}
                    - {os: macos-12}
                    - {os: windows-latest}
                    - {os: windows-2022}
                    - {os: windows-2019}
                    - {os: ubuntu-latest}   
                    - {os: ubuntu-24.04}   
                    - {os: ubuntu-22.04}   
                    - {os: ubuntu-20.04}   

        defaults:
            run:
                shell: bash -l {0}       

        steps:
            - uses: actions/checkout@v4
                
            - name: Setup Mambaforge
              uses: conda-incubator/setup-miniconda@v3
              with:
                  miniforge-version: latest
                  activate-environment: popsim
                  use-mamba: true
                  python-version: ${{ matrix.python-version }}

            - name: MacOS arm64 - Install llvm-openmp using Conda
              if: ${{ matrix.config.os == 'macos-latest' }}
              run: |
                mamba install llvm-openmp
              
            - name: MacOS - Install PyTables using Conda
              if: ${{ startsWith(matrix.config.os, 'macos') }}
              run: |
                mamba install numpy=1.19.5 pytables=3.7.0

            - name: Install PopulationSim with pip
              run: |
                pip install .

            - name: Conda checkup
              run: |
                mamba info -a
                mamba list

            - name: pytest
              run: |
                pip install pytest coverage
                pytest

            - name: Run example_calm
              run: cd example_calm && python run_populationsim.py -c configs

            - name: Run example_calm in multiprocessing mode
              run: cd example_calm && python run_populationsim.py -c configs_mp -c configs

            - name: Run example_calm_repop
              run: |
                cp ./example_calm/output/pipeline.h5 example_calm_repop/output
                cd example_calm_repop && python run_populationsim.py 
            
            - name: Run example_survey_weighting
              run: cd example_survey_weighting && python run_populationsim.py
        
