name: CI

on:
    push:
        branches:
            - '*'
    
    pull_request:
        branches:
            - '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true # If another job in the above group wants to run, it will cancel the current job

jobs:
    build:
        runs-on: ${{ matrix.config.os }}

        name: ${{ matrix.config.os }} (python v${{ matrix.python-version }})

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9']
                config:
                    - {os: macos-latest}
                    - {os: windows-latest}
                    - {os: ubuntu-latest}          

        steps:
            - uses: actions/checkout@v4
                
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                # cache: 'pip' # caching pip dependencies   

            - name: Install HDF5 on MacOS
              if: ${{ matrix.config.os == 'macos-latest' }}
              run: |
                brew unlink pkg-config
                brew link --overwrite pkgconf
                brew install hdf5

            - name: Install PopulationSim with pip
              run: pip install .


            - name: Run example_calm
              run: cd example_calm && python run_populationsim.py -c configs
        
