name: CI

on:
    push:
        branches:
            - '*'
    
    pull_request:
        branches:
            - '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true # If another job in the above group wants to run, it will cancel the current job

jobs:
    build:
        runs-on: ${{ matrix.config.os }}

        name: ${{ matrix.config.os }} (python v${{ matrix.python-version }})

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9']
                config:
                    - {os: macos-latest}
                    - {os: windows-latest}
                    - {os: ubuntu-latest}   
        defaults:
            run:
                shell: bash -l {0}       

        steps:
            - uses: actions/checkout@v4
                
            - name: Setup Mambaforge
              uses: conda-incubator/setup-miniconda@v3
              with:
                  miniforge-version: latest
                  activate-environment: popsim
                  use-mamba: true
                  python-version: ${{ matrix.python-version }}

            - name: Conda checkup
              run: |
                mamba info -a
                mamba list
              
            - name: Install PyTables using Conda
              if: ${{ matrix.config.os == 'macos-latest' }}
              run: |
                mamba install pytables=3.8.0

            - name: Install PopulationSim with pip
              run: |
                pip install .


            - name: Run example_calm
              run: cd example_calm && python run_populationsim.py -c configs

            - name: Run example_calm in multiprocessing mode
              run: cd example_calm && python run_populationsim.py -c configs_mp -c configs
        
